### PR TITLE
Annoyances and Fixes

### PR DESCRIPTION
**Pull request by Toff-kun**

### CODE REVIEW

**Comment by Toff-kun** [comment]
Played around with user agent to make the warning show up. Seems to pop up for Edge v15.

**Comment by janchaloupka** [comment]
Nice! I though they check the browser version in JS so changing the user agent will not make a difference.

**Comment by Toff-kun** [comment]
That 'Unsupported message' popup affects the Search page by squashing it down, and hiding it with 'display: none' leaves the Search page squashed. Can't figure out a good way to fix that. Doesn't seem to affect other pages.

Update: Figured it out.

**Comment by janchaloupka** [comment]
Can I merge the pull request or do you plan to include more commits?

**Comment by Toff-kun** [comment]
At this moment I don't know what other changes I can make. Everything seems to be working properly except for Daily Mix on mobile, which gives a blank page. Could be the outdated browser thing. Feel free to merge.

**Comment by janchaloupka** [comment]
Awesome, I will create separate issue for the blank Daily Mix page but I think it will be very hard if not impossible to fix because of the WM limited debugging.

**Pull request merged**
