### PR TITLE
QoL improvements and fixes

### PR DESCRIPTION
**Pull request by Toff-kun**
- Expanded Amoled Dark Mode to Now Playing Bar, Search Input Box and Artist pages;
- moved popup notifications below the Status bar to avoid text overlapping;
- overflow: hidden prevents scrolling in Edge, removed it;
- other minor content alignments.

### CODE REVIEW

**Comment by Toff-kun** [comment]
Great idea with the Amoled mode, loving it!

---

By the way, do we really need those ad banners? They take a lot of screen space and look pretty ugly, with some weird background placeholder of sorts being misaligned with the actual banners. I couldn't find how to fix it.
I would just go with
```
.Root__ads-container {
display: none; }
```
and be done with them. Or is it against the Store ToS?

**Comment by Tourniquet88** [comment]
I think if you hide the ad banners, the App might get blocked. Didn't Spotify change their EULA in that regard anyway some time ago?

**Comment by janchaloupka** [comment]
I haven't read the Spotify EULA, but I'm fairly sure, that removing ads is against their ToS. I don't think it's that big of a deal as only the free users are affected, and the ad banner is still less anoying than an audio ads between songs.

However maybe the banner could be made smaller so it doesn't take that much screen space.

**Review by janchaloupka — APPROVED** [review]

**Comment by Toff-kun** [comment]
Played around with the banner a bit, managed to fix the background and scaled it down until the full ad is visible. This way we get both a way less intrusive banner and a readable ad this way.

Looks like this now:
image

**Comment by janchaloupka** [comment]
Awesome, did you test scaling of the ad banner with different resolutions?

**Comment by Toff-kun** [comment]
I could only test on my 950 XL and in Edge on my PC. Seems to work identical, but I don't have the emulator installed to test various resolutions.
One thing I can't seem to figure out is how to move the banner up when the ConnectBar shows up (the green one saying you're listening on a different device). This bar moves the NowPlayingBar up which overlaps the banner.

**Comment by janchaloupka** [comment]
I believe when the Spotify Connect bar is visible either body or div.main get a special class indicating that the connect bar is visible. You can test multiple resolutions if you change scaling in your phone settings (Settings -> System -> Display).

**Comment by Toff-kun** [comment]
Are you planning to push these changes to the store anytime soon? :)

**Comment by janchaloupka** [comment]
Hello, yes I will push the changes to the store, I just had a very busy week,

**Comment by Toff-kun** [comment]
Sweet, I was just reading that article at AllAboutWindowsPhone and was wondering if I should post about the upcoming version there or just keep the intrigue and wait for the Store release. :) Glad to have you back.

**Pull request merged**
